/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_memorytestcpp_MainActivity */

#ifndef _Included_com_example_memorytest_MainActivity
#define _Included_com_example_memorytest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_memorytestcpp_MainActivity
 * Method:    _checkCpp_manually
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_memorytest_MainActivity__1checkCpp_1manually
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
